version: '3'
services:
  app:
    image: faas
    volumes:
      - .:/workdir
    ports:
      - "8501:8501"
    environment:
      - APIURL=http://api:8000
    entrypoint: streamlit run ui.py
  api:
    image: faas
    volumes:
      - .:/workdir
    ports:
      - "8000:8000"
    entrypoint: uvicorn api:app --reload
