version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8501:8501
    volumes:
      - .:/workdir
    environment:
      - ORS_SECRET=${ORS_SECRET}
    entrypoint: streamlit run app.py
